version: "3.7"
services :
    php73 :
        image : registry.cn-zhangjiakou.aliyuncs.com/imobie/php73
        container_name : php73
        volumes:
        - ~/volumes/www/:/var/www:rw
        - /etc/localtime:/etc/localtime
        - ~/volumes/php/7.3/log:/phplog
        links:
        - db
        restart: always
        depends_on:
        - db
        - redis
        logging:
            driver: "json-file"
            options:
                max-size: "5m"
    nginx : 
        image : registry.cn-zhangjiakou.aliyuncs.com/imobie/nginx-1.19
        container_name : nginx
        ports :
        - "80:80"
        - "443:443"
        restart: always
        volumes:
        - /etc/localtime:/etc/localtime
        - ~/volumes/nginx/conf.d:/etc/nginx/conf.d
        - ~/volumes/nginx/logs:/etc/nginx/logs
        - ~/volumes/www:/var/www:rw
        - ~/volumes/nginx/logrotate:/etc/logrotate.d/
        - ~/volumes/nginx/crontabs/:/var/spool/cron/crontabs/
        links:
        - redis
        - php73
        depends_on:
        - redis
        - php73
        logging:
            driver: "json-file"
            options:
                max-size: "5m"
    db:
        image : mysql:5.7.28
        container_name : mysql
        restart : always
        ports :
        - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: henglxm123!
        volumes:
        - ~/volumes/mysql:/var/lib/mysql
        - /etc/localtime:/etc/localtime
        logging:
            driver: "json-file"
            options:
                max-size: "5m"
    redis:
        image: redis
        container_name : redis
        restart: always
        volumes:
        - ~/volumes/redis:/data
        - /etc/localtime:/etc/localtime
        ports:
        - 6379:6379
        logging:
            driver: "json-file"
            options:
                max-size: "5m"
